.PHONY: doc

doc: desc.xml
	fpdoc --package=DEngine --input=OPENGL\DGraph.pas --input=DUtils.pas --input=WINDOWS\DWinApi.pas --input=DCamera2D.pas --input=DDebug.pas --input=DFont.pas --input=DIntersection.pas --input=FPC\DMath.pas --input=DSound.pas --descr=Desc.xml
