.PHONY: all

all:
	m4 -I ..\trunk\source\m4\ declare.m4 > declare.html

translator.html:
	m4 -I ..\trunk\source\m4\ translator.m4 > translator.html

mazejourney.txt:
	m4 -I ..\trunk\source\m4\ mazejourney.m4 > mazejourney.txt
